server:
    port: 8080
spring:
    datasource:
        password: password
        url: jdbc:postgresql://localhost:5332/customer
        username: clementlee
    jpa:
        hibernate:
            ddl-auto: create-drop # create and destroy the schema at the end of the session
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
    main:
        web-application-type: servlet
